//! Every vanilla item, and the creative inventory.
//!
//! The data comes from `data/items.json`, generated by `tools/item_data.py`
//! from PocketMine's BedrockData (CC0). Item network IDs are whatever the
//! ItemRegistry packet says, so data from a slightly older release works;
//! items added since are simply unknown.

use std::collections::HashMap;
use std::sync::LazyLock;

use base64::Engine as _;
use base64::engine::general_purpose::STANDARD;
use mistvale_protocol::block::{BlockState, StateValue};
use mistvale_protocol::packets::{
    CreativeContent, CreativeGroup, CreativeItem, CreativeItemStack, ItemEntry, ItemRegistry,
};
use serde::Deserialize;

const DATA: &str = include_str!("../data/items.json");

/// An item the server knows.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ItemType {
    pub name: String,
    pub network_id: i16,
    version: i32,
    component_based: bool,
    /// Components as encoded network NBT, for component-based items.
    components: Option<Vec<u8>>,
    /// The most a stack of it holds.
    pub max_stack: u8,
    /// For block items, the block state it places.
    pub block: Option<BlockState>,
    /// That block state's network ID.
    pub block_network_id: Option<u32>,
}

/// An item of the creative inventory.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct CreativeEntry {
    pub network_id: i16,
    pub metadata: u32,
}

/// The item registry: every item by network ID and by name, and the
/// creative inventory.
#[derive(Debug)]
pub struct Items {
    types: Vec<ItemType>,
    by_id: HashMap<i16, usize>,
    by_name: HashMap<String, usize>,
    creative_groups: Vec<CreativeGroup>,
    /// Creative items; creative network ID `n` is entry `n - 1`.
    creative: Vec<(CreativeEntry, u32)>,
}

/// The registry, loaded on first use.
pub fn items() -> &'static Items {
    static ITEMS: LazyLock<Items> =
        LazyLock::new(|| Items::parse(DATA).expect("data/items.json is valid"));
    &ITEMS
}

impl Items {
    pub fn get(&self, network_id: i16) -> Option<&ItemType> {
        self.by_id.get(&network_id).map(|&index| &self.types[index])
    }

    pub fn by_name(&self, name: &str) -> Option<&ItemType> {
        self.by_name.get(name).map(|&index| &self.types[index])
    }

    pub fn len(&self) -> usize {
        self.types.len()
    }

    pub fn is_empty(&self) -> bool {
        self.types.is_empty()
    }

    /// The creative item with creative network ID `id`.
    pub fn creative(&self, id: u32) -> Option<CreativeEntry> {
        let index = usize::try_from(id.checked_sub(1)?).ok()?;
        self.creative.get(index).map(|(entry, _)| *entry)
    }

    /// Every block state an item places.
    pub fn block_states(&self) -> impl Iterator<Item = &BlockState> {
        self.types.iter().filter_map(|item| item.block.as_ref())
    }

    /// The ItemRegistry packet: every item, sent with StartGame.
    pub fn registry_packet(&self) -> ItemRegistry {
        ItemRegistry {
            items: self
                .types
                .iter()
                .map(|item| ItemEntry {
                    name: item.name.clone(),
                    runtime_id: item.network_id,
                    component_based: item.component_based,
                    version: item.version,
                    components: item.components.clone(),
                })
                .collect(),
        }
    }

    /// The CreativeContent packet: the creative inventory's groups and items.
    pub fn creative_packet(&self) -> CreativeContent {
        CreativeContent {
            groups: self.creative_groups.clone(),
            items: self
                .creative
                .iter()
                .zip(1..)
                .map(|((entry, group), network_id)| CreativeItem {
                    network_id,
                    item: self.creative_stack(entry.network_id, entry.metadata),
                    group: *group,
                })
                .collect(),
        }
    }

    /// One of an item as the creative inventory shows it.
    fn creative_stack(&self, network_id: i16, metadata: u32) -> CreativeItemStack {
        let item = self.get(network_id);
        CreativeItemStack {
            network_id,
            count: 1,
            metadata,
            block_runtime_id: item.and_then(|item| item.block_network_id).unwrap_or(0),
            shield: item.is_some_and(|item| item.name == SHIELD),
        }
    }

    fn parse(json: &str) -> Result<Self, String> {
        let data: RawData = serde_json::from_str(json).map_err(|err| err.to_string())?;
        let mut items = Self {
            types: Vec::with_capacity(data.items.len()),
            by_id: HashMap::new(),
            by_name: HashMap::new(),
            creative_groups: Vec::new(),
            creative: Vec::new(),
        };
        for raw in data.items {
            let block = raw.block.map(RawBlock::state).transpose()?;
            let components = raw
                .components
                .map(|encoded| STANDARD.decode(encoded).map_err(|err| err.to_string()))
                .transpose()?;
            let index = items.types.len();
            items.by_id.insert(raw.id, index);
            items.by_name.insert(raw.name.clone(), index);
            items.types.push(ItemType {
                block_network_id: block.as_ref().map(BlockState::network_id),
                name: raw.name,
                network_id: raw.id,
                version: raw.version,
                component_based: raw.component_based,
                components,
                max_stack: raw.max_stack.max(1),
                block,
            });
        }

        let id_of = |name: &str| {
            items
                .by_name(name)
                .map(|item| item.network_id)
                .ok_or_else(|| format!("unknown item {name}"))
        };
        let mut groups = Vec::with_capacity(data.creative_groups.len());
        for group in data.creative_groups {
            let icon = match group.icon {
                Some(icon) => items.creative_stack(id_of(&icon.item)?, 0),
                None => CreativeItemStack::default(),
            };
            groups.push(CreativeGroup {
                category: group.category,
                name: group.name,
                icon,
            });
        }
        let mut creative = Vec::with_capacity(data.creative_items.len());
        for entry in data.creative_items {
            let network_id = id_of(&entry.item)?;
            creative.push((
                CreativeEntry {
                    network_id,
                    metadata: entry.meta,
                },
                entry.group,
            ));
        }
        items.creative_groups = groups;
        items.creative = creative;
        Ok(items)
    }
}

/// The shield, whose item data carries an extra field on the wire.
pub const SHIELD: &str = "minecraft:shield";

#[derive(Deserialize)]
struct RawData {
    items: Vec<RawItem>,
    creative_groups: Vec<RawGroup>,
    creative_items: Vec<RawCreativeItem>,
}

#[derive(Deserialize)]
struct RawItem {
    name: String,
    id: i16,
    version: i32,
    component_based: bool,
    components: Option<String>,
    max_stack: u8,
    block: Option<RawBlock>,
}

#[derive(Deserialize)]
struct RawBlock {
    name: String,
    /// `[name, type, value]`, type being `byte`, `int` or `string`.
    states: Vec<(String, String, serde_json::Value)>,
}

impl RawBlock {
    fn state(self) -> Result<BlockState, String> {
        let mut state = BlockState::new(self.name);
        for (name, kind, value) in self.states {
            let value = match (kind.as_str(), &value) {
                ("byte", serde_json::Value::Number(n)) => n
                    .as_i64()
                    .and_then(|n| u8::try_from(n).ok())
                    .map(StateValue::Byte),
                ("int", serde_json::Value::Number(n)) => n
                    .as_i64()
                    .and_then(|n| i32::try_from(n).ok())
                    .map(StateValue::Int),
                ("string", serde_json::Value::String(s)) => Some(StateValue::String(s.clone())),
                _ => None,
            }
            .ok_or_else(|| format!("bad state {name} of {}: {kind} {value}", state.name))?;
            state = state.with(name, value);
        }
        Ok(state)
    }
}

#[derive(Deserialize)]
struct RawGroup {
    category: u8,
    name: String,
    icon: Option<RawIcon>,
}

#[derive(Deserialize)]
struct RawIcon {
    item: String,
}

#[derive(Deserialize)]
struct RawCreativeItem {
    item: String,
    meta: u32,
    group: u32,
}

#[cfg(test)]
mod tests {
    use mistvale_protocol::packet::Encode as _;

    use super::*;

    #[test]
    fn the_registry_holds_vanilla_items_with_vanilla_ids() {
        let items = items();
        assert!(items.len() > 1500, "{}", items.len());
        let stone = items.by_name("minecraft:stone").unwrap();
        assert_eq!(stone.network_id, 1);
        assert_eq!(
            stone.block_network_id,
            Some(BlockState::new("minecraft:stone").network_id())
        );
        let sword = items.by_name("minecraft:diamond_sword").unwrap();
        assert_eq!(sword.max_stack, 1);
        assert_eq!(sword.block, None);
        assert_eq!(items.get(sword.network_id).unwrap().name, sword.name);
        assert_eq!(
            items.by_name("minecraft:ender_pearl").unwrap().max_stack,
            16
        );
        // A block with states places its creative state.
        let log = items.by_name("minecraft:oak_log").unwrap();
        assert_eq!(
            log.block,
            Some(
                BlockState::new("minecraft:oak_log")
                    .with("pillar_axis", StateValue::String("y".into()))
            )
        );
    }

    #[test]
    fn component_based_items_carry_their_components() {
        let apple = items().by_name("minecraft:apple").unwrap();
        assert!(apple.component_based);
        let components = apple.components.as_ref().unwrap();
        // A nameless root compound in network NBT.
        assert_eq!(components[..2], [10, 0]);
    }

    #[test]
    fn creative_items_are_numbered_from_one() {
        let items = items();
        assert_eq!(items.creative(0), None);
        let first = items.creative(1).unwrap();
        assert_eq!(
            items.get(first.network_id).unwrap().name,
            "minecraft:oak_planks"
        );
        let packet = items.creative_packet();
        assert!(packet.items.len() > 1500);
        assert!(
            packet
                .items
                .iter()
                .all(|item| (item.group as usize) < packet.groups.len())
        );
        assert_eq!(items.creative(packet.items.len() as u32 + 1), None);
        // Both packets encode.
        assert!(packet.encode().len() > 10_000);
        assert!(items.registry_packet().encode().len() > 10_000);
    }
}
